# Generated by Django 2.1.5 on 2020-04-03 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200403_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_publised',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 16, 56, 37, 639976), verbose_name='date published'),
        ),
    ]
