# Generated by Django 2.1.5 on 2020-04-04 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200404_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 17, 41, 29, 922987), verbose_name='date published'),
        ),
    ]
