# Generated by Django 2.1.5 on 2020-04-04 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200404_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 17, 58, 9, 906380), verbose_name='date published'),
        ),
    ]
