# Generated by Django 3.0.3 on 2020-04-05 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200404_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 11, 28, 33, 465382), verbose_name='date published'),
        ),
    ]
