# Generated by Django 3.0.3 on 2020-04-06 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200405_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageInput_title', models.CharField(max_length=200)),
                ('imageInput_description', models.CharField(max_length=1000)),
                ('imageInput_published', models.DateTimeField(default=datetime.datetime(2020, 4, 6, 16, 59, 14, 520352), verbose_name='date publised')),
                ('imageInput_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 16, 59, 14, 520352), verbose_name='date published'),
        ),
    ]
