# Generated by Django 3.0.3 on 2020-04-09 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200406_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageInput',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 15, 2, 55, 591193), verbose_name='date published'),
        ),
    ]
