# Generated by Django 2.1.5 on 2020-04-23 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200423_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 0, 35, 57, 306341), verbose_name='date published'),
        ),
    ]
