# Generated by Django 2.1.5 on 2020-04-26 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200425_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 13, 13, 18, 727095), verbose_name='date published'),
        ),
    ]
